markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "Rakefile"]
title : Recommendations API

BODDHI :
  version : 0.1
  BASE_PATH : false
  ASSET_PATH : assets/themes/boddhi

collections:
  docs:
    output: true
